// Turn an AI-generated character video into game-ready animation frames.
// Usage: node scripts/process-clip.cjs <video.mp4> <stateName>
// Steps: extract frames (12fps, audio dropped) -> chroma-key + crop + scale
// (via Electron worker) -> public/character/<state>/ -> regenerate manifest.
const { execFileSync, spawnSync } = require("child_process");
const path = require("path");
const fs = require("fs");
const os = require("os");
const ffmpeg = require("ffmpeg-static");

const [, , input, state] = process.argv;
if (!input || !state) {
  console.error("usage: node scripts/process-clip.cjs <video> <state>");
  process.exit(1);
}

const root = path.join(__dirname, "..");
const tmp = fs.mkdtempSync(path.join(os.tmpdir(), "clip-"));
const outDir = path.join(root, "public", "character", state);

console.log("1/3 extracting frames (12fps, no audio)…");
execFileSync(ffmpeg, [
  "-i", input,
  "-vf", "fps=12,scale=-2:540",
  "-an",
  path.join(tmp, "raw-%03d.png"),
], { stdio: "pipe" });
console.log("   " + fs.readdirSync(tmp).length + " raw frames");

console.log("2/3 removing background + cropping (Electron worker)…");
fs.rmSync(outDir, { recursive: true, force: true });
const res = spawnSync("npx", ["electron", path.join(__dirname, "clip-key.cjs")], {
  env: { ...process.env, CLIP_IN: tmp, CLIP_OUT: outDir, CLIP_STATE: state },
  encoding: "utf8",
});
const done = /FRAMES_WRITTEN:(\d+)/.exec(res.stdout + res.stderr);
if (!done) {
  console.error(res.stdout, res.stderr);
  process.exit(1);
}
console.log("   " + done[1] + " clean frames -> public/character/" + state);

console.log("3/3 regenerating sprite manifest…");
const charDir = path.join(root, "public", "character");
const states = fs.existsSync(charDir)
  ? fs.readdirSync(charDir).filter((d) => fs.statSync(path.join(charDir, d)).isDirectory())
  : [];
const manifest = {};
for (const s of states) {
  const frames = fs.readdirSync(path.join(charDir, s)).filter((f) => f.endsWith(".png")).sort();
  manifest[s] = {
    frames: frames.map((f) => `./character/${s}/${f}`),
    fps: 12,
    pingpong: true,
  };
}
const ts =
  "// AUTO-GENERATED by scripts/process-clip.cjs — do not edit by hand.\n" +
  "export interface SpriteAnim { frames: string[]; fps: number; pingpong: boolean }\n" +
  "export const SPRITES: Record<string, SpriteAnim> = " +
  JSON.stringify(manifest, null, 2) +
  ";\n";
fs.mkdirSync(path.join(root, "src", "generated"), { recursive: true });
fs.writeFileSync(path.join(root, "src", "generated", "sprites.ts"), ts);
fs.rmSync(tmp, { recursive: true, force: true });
console.log("done ✓ states with sprites: " + states.join(", "));
